### ISSUE TITLE
Make a list of stitching technologies and compare their performance and accuracy on our dataset

### ISSUE THREAD

**Issue by zacharylazzara** [carboncopies/BrainGenix-STS#11]
After the DataLoader is done, we can then compare the stitching technologies. For this stage we'll only use one layer (and likely only part of one layer instead of the entire layer, since each layer has a lot of data and we don't need to use all of it for testing, at least not at this stage).

What we want to do is see which stitching technology is the most performant and accurate. We want accuracy over performance, but it may be useful to still retain the option for lower accuracy at higher performance (as long as the default option is for the highest accuracy possible even at the expense of performance).

Ultimately we want to produce a class or function which takes in two X, Y coordinate tuples (a start and end tuple), then produces an image within the specified 2D coordinate range. Or perhaps takes two X, Y, Z coordinate tuples and produces an array of layers within that area (which can then be stacked by another class).

**Comment by madmax3000** [comment]
using Fiji to do the stitching seems to work out for us

**Comment by madmax3000** [comment]
have to do documentation for fiji
